import pysam
a=pysam.AlignmentFile('/netscratch/dep_tsiantis/grp_gan/awad/todo/illumina_polishing/hirsuta/nanoplish_old/awad/second_round/q0/ch.m.bam','rb')
b=[]
for i in a.fetch():
        if i.is_reverse==True:
                        b.append([i.reference_name,i.reference_start,i.reference_end,i.query_name,i.mapping_quality,'-',i.cigarstring,i.query_sequence])
                            else:
                                            b.append([i.reference_name,i.reference_start,i.reference_end,i.query_name,i.mapping_quality,'+',i.cigarstring,i.query_sequence])
                                            def cigar(string):
                                                    ci,m,n=[],0,0
                                                        while n<len(string):
                                                                        base=string[n]
                                                                                    if base == 'D' or base == 'H' or base == 'I' or base == 'M' or base == 'N' or base == 'P' or base == 'S' or base == 'x' or base == '=':
                                                                                                            ci.append(string[m:n+1])
                                                                                                                                m=n+1
                                                                                                                                                    n=n+1
                                                                                                                                                                else:
                                                                                                                                                                                        n=n+1
                                                                                                                                                                                            return(ci)
                                                                                                                                                                                        c=list(open('/netscratch/dep_tsiantis/grp_gan/awad/todo/illumina_polishing/hirsuta/nanoplish_old/awad/second_round/q0/m.fa','rb'))
                                                                                                                                                                                        c=''.join(c[1:]).replace('\n','')     


                                                                                                                                                                                        for base in b:
                                                                                                                                                                                                seq=base[-1]
                                                                                                                                                                                                    cig=cigar(base[-2])
                                                                                                                                                                                                        st=int(base[1])
                                                                                                                                                                                                            en=int(base[2])
                                                                                                                                                                                                                ref=c[st:en+1]
                                                                                                                                                                                                                    new=[]
                                                                                                                                                                                                                        if len(cig)==1 and seq==ref:
                                                                                                                                                                                                                                        new=[new[0].replace('M','=')]
                                                                                                                                                                                                                                            elif len(cig)==1 and seq==ref:
                                                                                                                                                                                                                                                            n,m=0,1
                                                                                                                                                                                                                                                                        while n<len(seq):
                                                                                                                                                                                                                                                                                                m=1
                                                                                                                                                                                                                                                                                                                    while n<len(seq) and seq[n]==ref[n]:
                                                                                                                                                                                                                                                                                                                                                    n=n+1
                                                                                                                                                                                                                                                                                                                                                                                m=m+1
                                                                                                                                                                                                                                                                                                                                                                                                    new.append(str(m)+'=')
                                                                                                                                                                                                                                                                                                                                                                                                                        m=1
                                                                                                                                                                                                                                                                                                                                                                                                                                            while n<len(seq) and seq[n]!=ref[n]:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            n=n+1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        m=m+1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            new.append(str(m)+'X')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                elif len(cig)>1:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ns=0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            for ba in cig:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if ba[-1]=='I':
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ns=ns+int(ba[:-1])
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                new.append(ba)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    elif ba[-1]=='D':
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ns=ns-int(ba[:-1])
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                new.append(ba)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    nref=ref[ns:int(ba[:-1])]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                nseq=seq[ns:int(ba[:-1])]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            n,m=0,0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        while n<len(nseq):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                m=1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    while n<len(nseq) and nseq[n]==nref[n]:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    n=n+1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                m=m+1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    new.append(str(m)+'=')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        m=1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            while n<len(nseq) and seq[n]!=ref[n]:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            n=n+1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        m=m+1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            new.append(str(m)+'X')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                dd=base
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    dd[-2]=''.join(new)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        dd[-1]='\n'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            d.append(dd)
